server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customers/**
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970