server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customers/**
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**